#!/bin/bash

_kill_procs() {
  kill -TERM $chproc
  wait $chproc
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

# Use the width/height/depth
#XVFB_WHD=${XVFB_WHD:-1024x768x16}
XVFB_WHD=${XVFB_WHD:-1600x1200x32}

# Start Xvfb on display port 99
Xvfb :99 -ac -screen 1 $XVFB_WHD +extension RANDR -nolisten tcp &
xvfb=$!

export DISPLAY=:99
echo "xvfb-chrome file is setting the screen size $XVFB_WHD"

google-chrome-stable --no-sandbox $@ &
chproc=$!

wait $chproc
wait $xvfb
